### PR TITLE
fix gif serialization of non array responses

### PR DESCRIPTION
**Pull request by heyalexchoi**
translate was broken because Giphy::Gif.build_batch_from assumed all responses were arrays, but the response from translate is a hash.

```
➜  giphy git:(fix-translate) bundle exec rake test
/Users/alexchoi/.rbenv/versions/2.2.3/bin/ruby -S rspec ./spec/giphy/artist_spec.rb ./spec/giphy/cli_spec.rb ./spec/giphy/client_spec.rb ./spec/giphy/configuration_spec.rb ./spec/giphy/favorite_gif_spec.rb ./spec/giphy/flagged_gif_spec.rb ./spec/giphy/gif_by_id_spec.rb ./spec/giphy/gif_spec.rb ./spec/giphy/image_spec.rb ./spec/giphy/null_image_spec.rb ./spec/giphy/random_gif_spec.rb ./spec/giphy/request_spec.rb ./spec/giphy/response_spec.rb ./spec/giphy/search_spec.rb ./spec/giphy/special_gif_spec.rb
.................................................0
........................................................................Showing the GIF on your browser
..Showing the GIF on your browser
........

Finished in 0.09929 seconds
131 examples, 0 failures

Randomized with seed 64134


```

### CODE REVIEW

**Comment by heyalexchoi** [comment]
@sebasoga hey just wondering if you had any comments on this PR.

**Comment by schonstal** [comment]
The Travis build is failing because of an issue with old versions of ruby. It is resolved in https://github.com/sebasoga/giphy/pull/11/commits/32acd89a2c7324d172783ae115a4e3147b9048db

**Comment by sebasoga** [comment]
Hey @heyalexchoi, I'm terribly sorry for taking this long to get to your PR. I'll get to it this weekend. In the meantime would you mind fixing the conflict with `.travis.yml`?

**Comment by heyalexchoi** [comment]
resolved the conflict and removed older ruby versions from .travis file. builds were failing on 1.9.3.

**Comment by sogamoso** [comment]
Thanks!

**Pull request merged**
